"use strict";

module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_GATEWAY: "BAD_GATEWAY",
};
