import type { TaskItem } from "./types";

export const initialTasks: TaskItem[] = [
  {
    id: "task-1",
    title: "Kiểm tra nhiệt độ tủ lạnh & máy pha chế",
    description: "Ghi chép nhiệt độ tủ bảo quản sữa và cài đặt áp suất máy pha trước giờ mở cửa đón khách.",
    sourceType: "shift",
    assignedByName: "Quy trình chuẩn Ca Sáng",
    shiftName: "Ca Sáng (07:00 - 14:00)",
    branch: "HN-1",
    dueDate: "2026-08-17 08:00",
    status: "overdue",
    priority: "urgent",
    assignedToEmail: "shift_all",
    assignedToName: "Tất cả nhân sự trực Ca Sáng",
    createdAt: "2026-08-17 06:45",
    requirePhoto: true,
    proofPhotoUrl: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800",
    photoSubmittedBy: "Nguyễn Thu Hà (Nhân viên pha chế)",
    photoSubmittedAt: "2026-08-17 07:42",
  },
  {
    id: "task-2",
    title: "Đối soát chứng từ hóa đơn kế toán tuần 2 tháng 8",
    description: "Kiểm tra hóa đơn đầu vào nguyên vật liệu cà phê, sữa tươi và bánh ngọt để nộp cho kế toán trưởng.",
    sourceType: "manager",
    assignedByName: "Vũ Thành Công (Quản lý)",
    branch: "HN-1",
    dueDate: "2026-08-17 17:30",
    status: "pending",
    priority: "high",
    assignedToEmail: "trang.pq@company.com",
    assignedToName: "Phạm Quỳnh Trang",
    createdAt: "2026-08-17 08:15",
    requirePhoto: false,
  },
  {
    id: "task-3",
    title: "Tiếp nhận và hướng dẫn nhân viên thử việc mới",
    description: "Bàn giao đồng phục, thẻ ra vào văn phòng và hướng dẫn sử dụng máy chấm công & app nội bộ HRM.",
    sourceType: "manager",
    assignedByName: "Vũ Thành Công (Quản lý)",
    branch: "HN-1",
    dueDate: "2026-08-18 10:00",
    status: "pending",
    priority: "normal",
    assignedToEmail: "duc.hm@company.com",
    assignedToName: "Hoàng Minh Đức",
    createdAt: "2026-08-17 09:00",
    requirePhoto: false,
  },
  {
    id: "task-4",
    title: "Tổng vệ sinh quầy pha chế & sắp xếp bàn ghế sảnh chính",
    description: "Lau sạch bề mặt kính, khử khuẩn các khay để cốc và dọn dẹp khu vực order trước khi kết thúc ca.",
    sourceType: "shift",
    assignedByName: "Quy trình chuẩn Ca Chiều",
    shiftName: "Ca Chiều (14:00 - 22:00)",
    branch: "HN-1",
    dueDate: "2026-08-17 21:45",
    status: "pending",
    priority: "normal",
    assignedToEmail: "shift_all",
    assignedToName: "Tất cả nhân sự trực Ca Chiều",
    createdAt: "2026-08-17 14:00",
    requirePhoto: true,
    proofPhotoUrl: "https://images.unsplash.com/photo-1556742049-0a67c5574f73?w=800",
    photoSubmittedBy: "Hoàng Minh Đức (Nhân viên phục vụ)",
    photoSubmittedAt: "2026-08-17 21:30",
  },
  {
    id: "task-5",
    title: "Bàn giao chìa khóa & tiền mặt ca sáng cho quản lý",
    description: "In phiếu kết ca từ máy POS, đếm tiền mặt trong két và ký biên bản giao ca với quản lý trực.",
    sourceType: "shift",
    assignedByName: "Quy trình chuẩn Ca Sáng",
    shiftName: "Ca Sáng (07:00 - 14:00)",
    branch: "HN-1",
    dueDate: "2026-08-17 14:15",
    status: "pending",
    priority: "high",
    assignedToEmail: "shift_all",
    assignedToName: "Tất cả nhân sự trực Ca Sáng",
    createdAt: "2026-08-17 07:00",
    requirePhoto: true,
  },
  {
    id: "task-6",
    title: "Báo cáo doanh thu & tổng kết công nợ tuần cho Ban Giám Đốc",
    description: "Tổng hợp số liệu từ 3 chi nhánh, phân tích các chỉ tiêu vượt định mức và đề xuất khen thưởng tuần.",
    sourceType: "manager",
    assignedByName: "Trần Minh Tuấn (Admin)",
    branch: "HN-1",
    dueDate: "2026-08-17 09:00",
    status: "completed",
    priority: "urgent",
    assignedToEmail: "manager@company.com",
    assignedToName: "Vũ Thành Công",
    completedAt: "2026-08-17 08:50",
    createdAt: "2026-08-16 16:30",
    requirePhoto: true,
    proofPhotoUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800",
    photoSubmittedBy: "Vũ Thành Công (Quản lý chi nhánh)",
    photoSubmittedAt: "2026-08-17 08:45",
  },
  {
    id: "task-7",
    title: "Kiểm kê số lượng hàng tồn kho nguyên vật liệu",
    description: "Đếm số túi hạt cà phê Robusta và Arabica trong kho phụ, lập biên bản nhập thêm cho tuần tới.",
    sourceType: "manager",
    assignedByName: "Lê Văn An (Quản lý)",
    branch: "HN-2",
    dueDate: "2026-08-18 11:30",
    status: "pending",
    priority: "high",
    assignedToEmail: "ngoc.tb@company.com",
    assignedToName: "Trần Bích Ngọc",
    createdAt: "2026-08-17 10:15",
    requirePhoto: true,
  },
];
